### ISSUE TITLE
[Enhancement] Export to Excel with each checklist item getting its own row? 

### ISSUE THREAD

**Issue by mikeurbonas** [trapias/TrelloExport#10]
This request probably is _much_ easier said than done, but... Might it be possible to render checklist items so they each have their own row? 

Trello does not let users specify a due date for individual checklist items which is a major issue for me. As a hack I can manually enter due dates in a common way for each checklist item, export to Excel and go from there to create a list of individual steps per project sorted by due date. However, for that to work, ideally I would have each checklist item rendered in Excel in its own row. 

Here is a screenshot showing current and desired Trello Excel export. It would be ideal if the contents of all other columns were simply repeated for each checklist line item. And no need to touch the beginning text before the first item; e.g., _Checklist (4 Items)_ :)

![2016-07-01_11-59-39](https://cloud.githubusercontent.com/assets/13050709/16528030/0b5fa478-3f88-11e6-8e9e-46cf4cd37aee.jpg)

Thanks for reviewing this enhancement request. :)

**Comment by trapias** [comment]
@mikeurbonas that's certainly possible!

Maybe I can add an option to trigger one of the two methods to export checklist items to Excel, so that who does not want to have duplicate rows can keep the old result. Will think about this, and work on it within a few days.

Thanks for your help!

**Comment by trapias** [comment]
@mikeurbonas please take a look at new version 1.9.24: it has a new option to export checklist items as rows, for Excel export only. Should work, but consider it as a beta ;-)

**Comment by trapias** [comment]
Implemented in version 1.9.24
