### ISSUE TITLE
hope to adjust DUE field output format ...

### ISSUE THREAD

**Issue by Chiwen6826** [trapias/TrelloExport#12]
Now format is like "2016-12-31T04:00:00.000Z". Hope adjust to "2016-12-13" only. 

Advise, please.

Chiwen Chen, Taiwan

**Comment by trapias** [comment]
@Chiwen6826 in what export format would you like to do so, Excel or other?

In Excel it would be easy to modify shown values via some function, did you try this?

**Comment by Chiwen6826** [comment]
Thanks for reply. Export to EXCEL format. Hope to like another Chrome extension "Export for Trello" displayed in 2016/12/31 directly (i.e. without extra function convert) using *yyyy/mmm/dd date format(actually value is 2016/12/31 12:00:00 PM). Advise, please.
