### ISSUE TITLE
[Bug] DoneTime not working

### ISSUE THREAD

**Issue by federicokeen** [trapias/TrelloExport#20]
After exporting, the DonyTime column has values like `P22DT21H16M23S` for cards that are marked as Done.

**Comment by trapias** [comment]
Done time is formatted as per ISO8601, please see http://trapias.github.io/blog/trelloexport-1-9-13.

**Comment by federicokeen** [comment]
Thanks sorry

**Comment by trapias** [comment]
@federicokeen no reason to be sorry :-) I thought ISO8601 was a good way to format durations, but suggestions are always welcome.

Thanks,
al.
