### ISSUE TITLE
Save TrelloExport Settings

### ISSUE THREAD

**Issue by jas0512** [trapias/TrelloExport#24]
We use trello export on a daily basis so thank you. We put the same settings in each time but it does take some time to put in the unique settings for our report. Is there a way to save the type of settings we would like for each report so we dont have to start new each time? Let me know. Thanks!

**Comment by moseres** [comment]
I agree this would be very useful. Also:

-when I make the selection from the dropdown menu, the menu does not disappear, so I cannot choose further options (which are behind the menu)

-the export only one list menu contains archived lists also which makes finding the right list in the menu more difficult

Great extension otherwise, thank you!!!

**Comment by trapias** [comment]
@jas0512 @moseres working on persisting options to localstorage: at the moment I save the selected export mode and CSS, will add some more - suggestions welcome!

**Comment by trapias** [comment]
@moseres sorry I didn't understand, can you give details about "the menu does not disappear, so I cannot choose further options (which are behind the menu)" ?

I shall filter out archived cards when the flag is not checked actually, will fix this thanks for reporting!

**Comment by moseres** [comment]
Hi, @trapias - sorry I'm a beginner here. Can I send a printscreen of the problem?

**Comment by moseres** [comment]
![image](https://user-images.githubusercontent.com/36104522/36645452-5789d982-1a69-11e8-98d8-cfc6e19320d3.png)

Here is the issue:

I select my options moving from top to bottom, and when I get to "Export Columns", I click on the dropdown, select what I want, and I cannot make the dropdown menu disappear, it lingers on the page. So it covers all other options (a tiny bit of the Export button is there, but if I push that, I cannot choose any other options). Is this more clear now? Thank you!

**Comment by trapias** [comment]
@moseres sorry for the long time, if you just press the button by which you open the columns list again, doesn't it collapse the list?

**Comment by trapias** [comment]
Closed with version 1.9.43, please reopen if not solved
