### ISSUE TITLE
Can't format custom date field in Excel

### ISSUE THREAD

**Issue by megara11** [trapias/TrelloExport#26]
I'm trying to only show the date (not the time) after I export to Excel, but Excel won't let me format it. I think there's something wrong with the export data seeing as I can format Trello's original due date field just fine. Here's a screenshot of the exported date field that cannot be formatted.

Can this be fixed?
![screen shot 2017-07-10 at 4 32 15 pm](https://user-images.githubusercontent.com/30059139/28041411-e9037642-658e-11e7-907d-d28b373c291b.png)

**Comment by trapias** [comment]
@megara11 trelloexport should format dates with your browser locale, what is yours?

**Comment by trapias** [comment]
Working properly AFAIK, pls reopen if you have issues
