### ISSUE TITLE
"Done" column feature not working for archived cards

### ISSUE THREAD

**Issue by ddickersonrealpropertymgt** [trapias/TrelloExport#28]
When pulling archived cards, the "done," "doneby," and "donetime" column features do not function although this data is still stored in the trello board. Attached is an export showing this issue. Workaround of restoring all archived cards is untenable because of volume. 
[TrelloExport_20170728165926.xlsx](https://github.com/trapias/TrelloExport/files/1185206/TrelloExport_20170728165926.xlsx)

**Comment by trapias** [comment]
Just made a check with 1.9.39 and found it works correctly
