### ISSUE TITLE
Some Cards are totally missing comments

### ISSUE THREAD

**Issue by rubenkostucki** [trapias/trelloExport#3]
First of: massive improvement from Ilad's code
Second: I've increased the limit to 1,000,000,000 for commentLimit in order to be sure that all comments would be exported from my Trello Board with 230 cards and many many comments.

For some unknown reasons, some Trello cards are missing all or parts of the comments in the .csv file. I've tried to find a pattern but can't seem to find any.

Do you have any idea why this may be the case?

**Comment by trapias** [comment]
can you provide a sample board with which you have the problem?

**Comment by rubenkostucki** [comment]
Hey Trapias,

Sadly this Trello board contains private information.

Is there any other way you could explore doing this? I must have millions
of lines, that's all...

Thanks



*___________________________*

*Ruben Kostucki, **Director of Growth*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>

**Comment by trapias** [comment]
@rubenkostucki you mean you have millions of comments per card? Mostly long or short comments? It would help to see a card with comments that are not exported, but of course not with private data. I'll check if i can quickly generate a card with so many comments with some script, I'd not do this manually ;-)

**Comment by rubenkostucki** [comment]
I have short and long comments (like 100-200 words max), but some cards have dozens of comments.
In what format would you like to see a card? 
I went on Trello, selected one of the cards that hadn't exported all the comments (it had only exported parts of it). I then exported it to JSON and went to http://konklone.io/json/. The .csv file I got from the export indeed contained all the comments. So both the JSON and the .csv contained all the comments if that single card was selected

**Comment by trapias** [comment]
@rubenkostucki the best for me would be to see such a card on any Trello board (I can create a test board, no problem) - there must be something causing some failure in reading data. I'm adding some debug logging later this evening, so we can begin testing

**Comment by rubenkostucki** [comment]
FYI there's many cards that don't have the comments and all of them contain
confidential data so not sure how I can help (I know, it's frustrating!).
I tried something else: I copied/moved that same card (the one which when
exported in JSON individually worked fine but not with the full export)
from one board to another and tried your export Excel but it didn't work.
If anything, it actually resulted in less comments being exported than
previously.



*___________________________*

*Ruben Kostucki, **Director of Growth*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>

**Comment by rubenkostucki** [comment]
Trapias, by the looks of it it's a Trello issue because in the JSON, not
all the comments appear for some reason... will get in touch with them

*___________________________*

*Ruben Kostucki, **Director of Growth*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>

**Comment by trapias** [comment]
I think it depends on how data is retrieved: of you get json for a single card maybe you get more data than what you have in a board json. Have to investigate what this means for processing time too.
Please be patient, this is in my to-do list!

**Comment by trapias** [comment]
@rubenkostucki sorry for such a long delay, I recently changed job and have no free time!
I think I should ask Trello for each card's data in order to be sure to get all comments, while at the moment I get the Board's son data.
I believe I can modify the code to do this, but I wonder if it makes sense: 1) export would be much slower and maybe timeouts could become an issue, 2) Excel has limits in the number of rows and sure in the length of cells (amount of text you can put in a cell), so putting in tons of comments could lead you to have an unusable spreadsheet, isn't it?

Wouldn't some different export method (xml?) better address the problem?

**Comment by trapias** [comment]
@rubenkostucki I did some investigations... can you please make a quick check for me?
If you look at the son for one of the boards where you have many comments (get the url from the address bar and append ".json" to get son data for the board), do the "comments" counters tell you the right amount of comments you have?
I mean, say you have 50000 comments on a card: in the Board json you see comments: 50000, or you see a lower counter (maybe 1000)?

**Comment by zehawki** [comment]
Another point to add to this discussion: 
1. When there are copied comments in a card, they dont show up in the export, however they show up fine in the original card's export. 
2. If a card has copied comments and newly written comments both, only the newly written comments show up in the export.

**Comment by trapias** [comment]
@zehawki what do you mean with "copied comments"? Copied how?
I need sample data, can you replicate the problem? I'm opening a test board on Trello

**Comment by trapias** [comment]
@zehawki I made my trill board for this project public, can you try to replicate the problem on this board? https://trello.com/b/MBnwUMwM/trelloexport

**Comment by zehawki** [comment]
Its very easy to replicate. Just copy a card with comments, then export.

**Comment by trapias** [comment]
@zehawki ok I replicated the problem, looking into it

**Comment by trapias** [comment]
@zehawki fixed with version 1.9.7

**Comment by trapias** [comment]
@rubenkostucki @zehawki new version 1.9.8 now gets data via Trello API, see readme: now all comments should be exported

**Comment by trapias** [comment]
@rubenkostucki @zehawki new version 1.9.9 should allow you to export all data, please let me know if you see other problems

**Comment by AliEmili** [comment]
Facing with the exact issue right now @trapias

**Comment by trapias** [comment]
@AliEmili can you share a board with me to check?
