### ISSUE TITLE
Export custom fields not working

### ISSUE THREAD

**Issue by tobalr** [trapias/TrelloExport#31]
Hi. 
Unfortunately I am unable to export custom fields.
Test trello board available here with two custom fields:
https://trello.com/invite/b/MgLng6dV/6ccb0a0b931f94b0035f3a4f9f8ce9d3/test

My export from v1.9.40
[TrelloExport_20180323204055.xlsx](https://github.com/trapias/TrelloExport/files/1843258/TrelloExport_20180323204055.xlsx)

Screenshot of export menu. 
When I mark the "custom fields" checkbox it will still show 26 columns.  
![image](https://user-images.githubusercontent.com/5293993/37850371-27e94be6-2edb-11e8-9f9d-e615be507a30.png)

Can you confirm this issue?

**Comment by trapias** [comment]
I have to work on custom fields, not working at the moment. Will fix asap!
