### ISSUE TITLE
Export to HTML WITHOUT the description.

### ISSUE THREAD

**Issue by computergecko** [trapias/TrelloExport#32]
Hi There,

When exporting to HTML, I only want the checklists to show up under each card.

However, the description field also shows up.

Is there a way to prevent the description from showing up?

Thanks!

**Comment by trapias** [comment]
@computergecko I can link exporting the description to the already existing flag "Export card info", or  add an option for that... maybe better a new option?

**Comment by computergecko** [comment]
That would be awesome!  Adding check box to whether you want the description or not!

Thanks!

**Comment by trapias** [comment]
Closed with version 1.9.43, please use a custom Twig template now
