### ISSUE TITLE
Export Button not working

### ISSUE THREAD

**Issue by isabeljordan** [trapias/TrelloExport#33]
Export button is frozen and not generating the Excel Doc. I've clicked multiple times, re-load the page. Existing issue from yesterday. Any suggestions/is this a bug?

<img width="815" alt="screen shot 2018-04-03 at 9 14 16 am" src="https://user-images.githubusercontent.com/38041263/38251447-7899185e-371f-11e8-9dcb-506a6be7a44f.png">

**Comment by trapias** [comment]
Could you please see the browser console(under developer tools) to see if any error is reported?
