### ISSUE TITLE
Custom Field values updates not Appear on Export

### ISSUE THREAD

**Issue by mclayton1121** [trapias/TrelloExport#34]
Prior to update when exported custom fields values appear.  Now when export only see values for custom fields entered prior to 3/27/18.  Anything entered on or after not exported.

**Comment by mikekonikoff** [comment]
Same for me, except the cutoff date is 3/2. Cards created after that date have custom fields, but the values won't export.

**Comment by trapias** [comment]
Custom fields not working, duplicate of #31
