### ISSUE TITLE
HTML Template Engine Integration?

### ISSUE THREAD

**Issue by richardkaplan** [trapias/TrelloExport#35]
HI - This is a terrific piece of software.

Any chance you would consider integrating it with an HTML template engine such as Twig or Handlebars or Smarty so the output can be customized by the user?

**Comment by trapias** [comment]
@richardkaplan I was thinking about this a couple of days ago, and was looking at [mustache.js](https://github.com/janl/mustache.js) - but there are options. I also played a little with Handlebars, sometimes ago... any recommendations?

**Comment by trapias** [comment]
Closed with version 1.9.43
