### ISSUE TITLE
Title of Card as Hypertext?

### ISSUE THREAD

**Issue by richardkaplan** [trapias/TrelloExport#36]
Hi

Currently each card has a number which is a link back to the Trello card.

Any chance that the entire title could be the active link rather than just the number?

**Comment by trapias** [comment]
I'd better implement #35, but can fix this in the meantime.

**Comment by richardkaplan** [comment]
Thanks!   Also - could there be an option - or separate field - for the hyperlink to be to the Link referenced inside the Card rather than to the Trello card?

**Comment by trapias** [comment]
Closed with version 1.9.43
