### ISSUE TITLE
Export not open

### ISSUE THREAD

**Issue by slepciu** [trapias/TrelloExport#39]
When I try to use export, I have such an error:
![image](https://user-images.githubusercontent.com/3042002/39099097-c4ea13ac-4674-11e8-957f-25f660f72f93.png)

**Comment by trapias** [comment]
@slepciu looks like you're not using a classic Trello URL, is that possible? Could you share this board URL with me to check? Are you getting this error on any board?

**Comment by slepciu** [comment]
Yes, the error is on each board. The url address is normal. I created a test board: https://trello.com/b/7bPa3qgT/test
The export works correctly from the side menu

**Comment by trapias** [comment]
@slepciu the side menu is the intended way to open TrelloExport, the button Chrome adds to its plugin bar does not run the app. How else are you trying to open it?

**Comment by trapias** [comment]
Closed with version 1.9.43
