### ISSUE TITLE
Order in checklist is incorrect

### ISSUE THREAD

**Issue by zehawki** [trapias/trelloExport#4]
Thanks a lot for this extension. 

Immediate problem I notice is that the order of items in checklist as displayed in Excel cell is incorrect, for all cards. Please see example below:

Trello original checklist:

![trello original checklist](https://cloud.githubusercontent.com/assets/8095144/7252075/058f7758-e84f-11e4-89b2-ff86b0136320.png)

And after it appears in Excel:

Progress/Status:
 - F2F 20-Apr at 3.30PM (Himanshu) (complete)
 - Telecon TBD (incomplete)
 - Offer sent (incomplete)
 - Offer accepted (incomplete)
 - Selected after tech rounds? (incomplete)
 - Shortlisted (complete)
 - HR interview TBD (incomplete)
 - Selected after HR interview? (incomplete)
 - Joining date TBD (incomplete)
 - F2F 16-04-2015, 2pm (Amit) (complete)
 - F2F TBD (Himanshu) (incomplete)

**Comment by trapias** [comment]
@zehawki I just pushed version 1.9.6 that solves this issue
