### ISSUE TITLE
DueComplete

### ISSUE THREAD

**Issue by Hiveist** [trapias/TrelloExport#41]
Hello,

Can you make Done Date to come not from Done column time but get the DueComplete function?

Thank you

**Comment by trapias** [comment]
@Hiveist as already found in issue #40 there’s no field in Trello data for the date when the card was marked completed, we only have a true/false flag named “dueComplete”.
Until Trello adds such a field, I cannot do anything.

Please see Trello API docs for the [card object](https://developers.trello.com/v1.0/reference#card-object)
