### ISSUE TITLE
< symbol showing as '&It;'

### ISSUE THREAD

**Issue by jamesmachin** [trapias/TrelloExport#42]
Hi,

edit: the description should state & l t ; **_(without spaces)_**

When using TrelloExport to export data from Trello we have the symbols <> around some of our data in the card description.
When downloading this it usually pulls ok as <>, but since today (30/04/18) this is pulling differently.

Example:
Data on card - PARENT SKU: <123456>
Data exported - PARENT SKU: & l t ; 123456> **_(without spaces)_**

Some pull through ok.
Is there a reason some of the < symbols are now exporting as &lt; ?

Thanks,
James

**Comment by trapias** [comment]
HTML export engine is all new now, using Twig templates: I do some encoding before sending data to the template engine, and am probably double-encoding something. 

A quick test with a board of mine did not show such a problem: would you please share a test board with me, so that I can test?

**Comment by jamesmachin** [comment]
I have created a test board and invited you to it.

I have tried downloading the data using TrelloExport and still having the same issue on this test board too.

**Comment by trapias** [comment]
I think I found the problem, will push an update in a few minutes

**Comment by jamesmachin** [comment]
Works ok now. 

Many thanks :)

**Comment by jamesmachin** [comment]
Hi @trapias 

Sorry to bother you again, but since the new update we have another encoding issue. 
Now all data is extracting with loads of hashtags in the data.

Example - SKU & # 5 8 ; & # 3 2 ; & # 6 0 (without spaces)

Please see example on the test board I shared with you when exporting the data.
