### ISSUE TITLE
Issue - Export to Excel - Special characters in text fields

### ISSUE THREAD

**Issue by geneva-data** [trapias/TrelloExport#43]
When exporting to Excel, special characters (markdown) are appearing in some text fields. This just started happening.

Before:
UI Customization   by clients

Now:

 UI & #32 ;Customization & # 32;by & #32;clients

**Comment by mikekonikoff** [comment]
This is making export unusable

**Comment by LechonIV** [comment]
[TrelloExport_20180504115115.xlsx](https://github.com/trapias/TrelloExport/files/1973983/TrelloExport_20180504115115.xlsx)
I'm having the same issue, making the reports based on the exports useless...

**Comment by LechonIV** [comment]
I'm having the same issue, making the reports based on the exports useless...
"

Offene&#32;F&#228;lle&#32;(Fall&#32;unbearbeitet&#44;&#32;Bearbeitung&#32;innerhalb&#32;von&#32;&#53;&#32;Werktagen)
--

"

**Comment by Stratboy1965** [comment]
I'm having the same issue, my reports is useless.

**Comment by trapias** [comment]
Encoding issue, sorry guys pushing a new release as soon as possible

**Comment by geneva-data** [comment]
Perfect! Thank you!
