### ISSUE TITLE
"Template set" not working.

### ISSUE THREAD

**Issue by Infotelecom** [trapias/TrelloExport#46]
When I put in "Template set" field your exmple set:
https://trapias.github.io/assets/TrelloExport/templates.json
everything works fine.
But if I copy this file to my place and put in in this field:
https://s3-eu-west-1.amazonaws.com/pliki.statyczne.naszej.strony.www/_trello/templates2.json
There is na error:
NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://s3-eu-west-1.amazonaws.com/pliki.statyczne.naszej.strony.www/_trello/templates2.json'. 0: undefined

**Comment by trapias** [comment]
@Infotelecom yes I get the same error and don't know why. I'm investigating this!

**Comment by trapias** [comment]
@Infotelecom the problem is actually explicit in the error, if you look in console (will improve the error message):

`No 'Access-Control-Allow-Origin' header is present on the requested resource`

I just made a test inspecting requests to the two URLs, and Github adds the header:

`
access-control-allow-origin: *
`

while AWS does not. Don't know if there's a way to add it at AWS, do you?

**Comment by trapias** [comment]
@Infotelecom looks like this can be solved by configuring CORS at AWS, see for example the first answer at [this question on StackOverflow](https://stackoverflow.com/questions/17533888/s3-access-control-allow-origin-header) and AWS [documentation about CORS](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-cors-configuration.html)

**Comment by Infotelecom** [comment]
Hi!
I've read it all. I've set up a new bucket and setup CORS on it.
https://s3-eu-west-1.amazonaws.com/trelloexport/templates2.json
Same error. 
I've looked into Fiddler - cannot see this header tag in aws request or github.io.
Any other ideas?

**Comment by Infotelecom** [comment]
HTTP/1.1 200 OK
x-amz-id-2: n+pKUTLYO13OctMm6vUH8YmZ9X+3LlVM6QaXiOepm2FBwSUHeikuHJiBQQmCFJUJ1kuCqSaKReM=
x-amz-request-id: 6D65B1D9E0220112
Date: Mon, 07 May 2018 18:53:33 GMT
**Access-Control-Allow-Origin:** *
Access-Control-Allow-Methods: GET
Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
Last-Modified: Mon, 07 May 2018 18:04:47 GMT
ETag: "12c8ac2da0400c9282674d17f3133d04"
Cache-Control: max-age=600
Accept-Ranges: bytes
Content-Type: application/json
Content-Length: 1102
Server: AmazonS3

but still no joy...
Same error.
Any ideas?

**Comment by trapias** [comment]
👍
