### ISSUE TITLE
Error 403 Trello Download

### ISSUE THREAD

**Issue by craigbowman2** [trapias/TrelloExport#47]
@trapias 

Good Morning,

When trying to export from Trello i am receiving the below message.

![error message](https://user-images.githubusercontent.com/39903057/40910868-2e279574-67e5-11e8-8421-0b1a59f2b4a0.JPG)

Could you please advise?

Thanks
Craig

**Comment by craigbowman2** [comment]
@trapias 

Good Morning,

Have you had chance to take a look at the above issue?

**Comment by trapias** [comment]
@craigbowman2 I made some tests and also get the error when exporting many cards. I'm investigating the problem, looks like something changed in Trello API limits.

**Comment by trapias** [comment]
@craigbowman2 could you please share with me a board where you get this problem? I'm getting the error on a board and always on the same cards, would like to better investigate

**Comment by craigbowman2** [comment]
@trapias 

https://trello.com/b/5BtG1pm8/qa-womens?menu=filter&filter=548

Will the link work?

**Comment by trapias** [comment]
@craigbowman2 no, you have to invite me to the board since it's not public - thanks

**Comment by craigbowman2** [comment]
@trapias 

An invite has been sent to you by Natalie Aukland.

I didn't have the authority

**Comment by craigbowman2** [comment]
@trapias 

Did the invite work?

**Comment by trapias** [comment]
@craigbowman2 yes thanks, but cannot go on with this now - will tell ASAP

**Comment by trapias** [comment]
@craigbowman2 still couldn't find the time to dig into this. The error appears on some lists only, and I suspect those lists have a lot of archived cards: is this your case? A test could be that of deleting those archived cards, then try to export again.

**Comment by craigbowman2** [comment]
@trapias 

Good Morning,

Yes it only seems to be on some boards.

We can't delete archived cards because in some cases they can get reopened.

Is there any way to increase the limit?

**Comment by trapias** [comment]
No, Trello limit is 1000 and cannot be changed. I'm trying to see if I can filter my requests, but cannot tell when I'll be able to - sorry, I'm very busy with my job.

**Comment by craigbowman2** [comment]
@trapias 

Ok.

I have asked my management to see if there is any chance we can delete any archived cards.

I will keep you updated.

Could you please do the same if you find time to look into the issue more.

**Comment by craigbowman2** [comment]
@trapias 

Is the 1000 limit for archived cards??

**Comment by jamesmachin** [comment]
Hi @trapias 

We download data from over five Trello boards using TrelloExport.
These boards all have a different number of cards (including archived), but this issue started happening on the same day for all the boards except one.

![image](https://user-images.githubusercontent.com/32671058/41234815-2a5b56d8-6d85-11e8-9612-554ad6beacfa.png)

Board 1 still downloads ok, but the others are having the above issue and the downloaded CSV is missing data from the boards.

Maybe this means there has been a change to Trello API limits?

Hope this helps your investigation.

**Comment by trapias** [comment]
@craigbowman2 @jamesmachin I finally found it, there was a change in Trello limits recently - see 
[https://trello.com/c/8MJOLSCs/10-limit-actions-for-cards-requests](https://trello.com/c/8MJOLSCs/10-limit-actions-for-cards-requests).

I'm pushing a new release within minutes.

**Comment by jamesmachin** [comment]
@trapias 
This new release works ok.
Many thanks for your help!
