### ISSUE TITLE
Remember the selected items of Export Column

### ISSUE THREAD

**Issue by bonxxbon** [trapias/TrelloExport#48]
As a reporter, I need to remember selected-export-column as I have a lot of fields each card (50+) but daily report does not need full fields.

Could you improve that feature?

**Comment by trapias** [comment]
@bonxxbon implemented in 1.9.54, on the Chrome Web Store within one hour from now

**Comment by bonxxbon** [comment]
I have checked it and it works more excellent than my expectation. Cool, thanks!

**Comment by trapias** [comment]
👍
