### ISSUE TITLE
Spent and Estimate columns not populated

### ISSUE THREAD

**Issue by SDMA-JH** [trapias/TrelloExport#49]
I'm trying to export the following from all of my Trello boards, but the Spent and Estimate columns are not populated with data on my larger boards. 

Organisation
Board
List
Title
Spent
Estimate
Created
Done
Members
Labels

I have tried various combinations of EXPORT options and refining the EXPORT COLUMNS. I have tried cleaning the local storage and deleting the test files from my Download folder, but I cannot get Spent and Estimate to be populated as I require.

**Comment by trapias** [comment]
@SDMA-JH do you mean you can get spent and estimate for some boards, but not for boards with large amount of cards? If so please share a test board with me, if not please clarify.
Thanks,
al.

**Comment by SDMA-JH** [comment]
HI,

Yes, I can get them for small boards but not large boards

Thanks,

Julia

**Comment by trapias** [comment]
@SDMA-JH please share a test board with me so that I can investigate the problem, thank you.
