### ISSUE TITLE
Trello Export not downloading

### ISSUE THREAD

**Issue by craigbowman2** [trapias/TrelloExport#50]
@trapias 

Good Morning,

When we try to download Trello via the Trello Export option it is just giving us a blank Excel file.

Could you please take a look.

Thanks

Craig Bowman.

**Comment by craigbowman2** [comment]
@jamesmachin

FYI

**Comment by trapias** [comment]
@craigbowman2 are you using latest version, 1.9.55 published a couple of days ago? I just made a test and can export to Excel, please give more details and a test board for me to replicate the error.

**Comment by craigbowman2** [comment]
Hi @trapias 

I have added you in to a test board I have just created called 'TEST BOARD'.

**Comment by craigbowman2** [comment]
@trapias 

I have the updated version of Export too

**Comment by trapias** [comment]
@craigbowman2 I just made a test on your board, and could successfully export to a valid Excel file - see screenshot.
Please try to clear localstorage with the button at the bottom of TrelloExport dialog: does this solve?

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2881610/44024647-28d17032-9eee-11e8-919c-5d97ae008b0e.png">

**Comment by craigbowman2** [comment]
@trapias 

Hi,

We have both tried what you recommended but it hasn't worked.

**Comment by trapias** [comment]
@craigbowman2 please check the browser console, are there any errors? Also pls tell what kind of export parameters are you using, e.g. current board and everything you select.
Finally are you on a Mac or Windows?

**Comment by craigbowman2** [comment]
@trapias 

There doesn't to be any errors on either computer. Everything was working OK on Friday.

Please see below image for the parameters we use for all except one of our boards. For the exception we just untick Archived Cards.

![image](https://user-images.githubusercontent.com/39903057/44027817-b6f28422-9eef-11e8-9efa-fc73ca038d7d.png)

We are on Windows.

Cheers.

**Comment by trapias** [comment]
@craigbowman2 I just made a couple of tests with my Windows PC, and still cannot see any issue.

I actually have no idea of what's happening there! Can you test with another PC?
I think you should try to clear the browser cache and TrelloExport localstorage (you could also clear all cookies using some extension like "HTML5 storage manager all in one" or similar), and maybe disinstall and then install again TrelloExport - 
Also, if you have other extensions installed, try disabling them - sometimes conflicts appear.
Let me know if you find any solution!

Thank you, 
al.

**Comment by trapias** [comment]
@craigbowman2 I finally understood where the problem was - a stupid bug, sorry.
Version 1.9.57 should really solve, please confirm.

**Comment by trapias** [comment]
@craigbowman2 actually resolved with 1.9.58

**Comment by jamesmachin** [comment]
@trapias this is working ok now since the update.

Many thanks.
