### ISSUE TITLE
Due Date Done field

### ISSUE THREAD

**Issue by adamscott74** [trapias/TrelloExport#52]
fantastic work on the extension, it has allowed me to extract with ease the data from Trello for reporting. For various security reason our organisation has not allowed several of the powerups so extracting them to excel is the ideal solution for reporting.

One of the extract fields we use is the 'Due Date' for the card which is clearly shown in the XLSX file when I export, however the 'Done' column which is present is always Blank.   Would this 'Done' column refer to when a Due Date is selected as completed?  If not is this field included anywhere as I have not been able to find it?
I've included a screenshot to show the field I am referring to, note it a Trello out of the box field not a custom field.
![capture](https://user-images.githubusercontent.com/42603758/44452178-30fc7c00-a639-11e8-8eb4-cf10cf1d174e.PNG)

**Comment by trapias** [comment]
@adamscott74  glad it helps you!
For the “done” column please check the wiki at 
https://github.com/trapias/TrelloExport/wiki/Done

Thanks,
Alberto.

**Comment by adamscott74** [comment]
thankyou Alberto.  I've tried this on several Trello boards I have some with a small number of cards and others with more adding new cards moving existing cards etc. Also changing the text string it looks for to define List column to use for the Done calculations.
For all of them it is still returning blanks in the Done, DoneBy and DoneTime columns.  Went through all the Troubleshooting options also, are there any tricks to getting those particular fields out (the other fields are fine)
[TrelloExport_20180823111014.xlsx](https://github.com/trapias/TrelloExport/files/2312465/TrelloExport_20180823111014.xlsx)
?

I attached an extract file as an example (I've scrubbed some of the data) of what was returned

regards
Adam...

**Comment by trapias** [comment]
@adamscott74 Done is detected when a card was created in a list, then moved to a "done" list. If you try to export for example the "Done" list from [TrelloExport board](https://trello.com/b/MBnwUMwM/trelloexport) you should see those columns populated.
If that's not working with your boards, maybe you can share one with me so that I can check?

**Comment by adamscott74** [comment]
ok, I've tried this across a few other Trello boards and can get it to work, though there does not appear to be a pattern as to why.  

I've added you to this board - https://trello.com/b/ZyPrUqzK/adam-automation-tasks.  It is one of the ones that is not work (but is not sensitive information), I tried to use the OTHER column as the basis for the Done calculations with no output.
(this board is much simpler than the others I have which have 50-100 
[TrelloExport_20180823154009.xlsx](https://github.com/trapias/TrelloExport/files/2313072/TrelloExport_20180823154009.xlsx)
and Checklists within them)

**Comment by trapias** [comment]
@adamscott74 I checked your board, and  I can see two problems.
The first is Trello API does not return an "updateCard" action for when that card was moved to the Done list: I can only see an "updateCheckItemStateOnCard" action for it.

The second is there's a mismatch: the list is named "OTHER", but the "completion action" was detected when you moved the card to a list named "DONE" - see the screenshot. Maybe you renamed the list? I think the "updateCard" action could not be available for this reason, thought I'm not sure.

![image](https://user-images.githubusercontent.com/2881610/44508147-81152600-a6ad-11e8-8703-743ed9d9f75b.png)

**Comment by adamscott74** [comment]
I moved and changed the names a few times which I am sure doe snot help, was trying to find a combination that worked.
The other boards I have are more static with the names so I do not expect that issue with them.

Are you able to expand on the first comment about the Trello API not returning an "updateCard" action for when that card was moved to the Done list: I can only see an "updateCheckItemStateOnCard" action for it.  Are you saying it normally does not do that, or for some reason it did not here?

**Comment by trapias** [comment]
@adamscott74 I load actions for cards included in the export set, and normally get "updateCard" actions in Trello API response: then I elaborate the action data and output to those columns in report.
As you say, for some reasons I get no actions of this type on that board: I actually don't know why, maybe actions are removed when you rename a list or something like that.
Let me know if you find something useful!

**Comment by adamscott74** [comment]
quick update Alberto.  One of the Boards that was not working I exported again today and have the details populated for a test card I created last week and moved into a Done column.  I believe the issue related to the timing of moving it to a column and also renaming columns, something you suggested above.   Thanks for the guidance to help get it resolved.

Adam...

**Comment by trapias** [comment]
@adamscott74 great, glad to hear! Thanks for the update,
Alberto.
