### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by WoodrowShigeru** [trapias/TrelloExport#53]
How is this extension supposed to work?

I've downloaded it from the Chrome webstore (assumingly the latest version of it) and reloaded my Trello board. What am I supposed to look at?

Should there be a link injected in the website? Should the extension icon next to Chrome's omnibox light up? Should there be a dump in the DevTools? The options menu item is grayed out, and the "TrelloExport" menu item leads me to your website.

I see a modal window in the screenshot displayed in the store and on your blog – but how do you open it? Must the Trello board be public for this exporter to work? Do I need to be a Trello premium user? The info in [this early blog post][1] on "How to use" seems to be outdated as the title-clicking only lets me rename my board. I don't see any option to share or export anywhere else either. Deactivating Ghostery and Adblocker didn't help either. What gives?

[1]: https://trapias.github.io/blog/trelloexport-trello-to-excel

**Comment by trapias** [comment]
@WoodrowShigeru you're right, it is not well documented. I now added a new page to the Wiki, please see [HowToUse](https://github.com/trapias/TrelloExport/wiki/HowToUse).

Regards,
Alberto.

**Comment by WoodrowShigeru** [comment]
I see it now.

Hm, as it turns out, Adblocker _was_ the culprit, after all. If I have it enabled, the menu item "Print and Export" doesn't even show up. (FYI)

Thanks for the fast answer.

**Comment by trapias** [comment]
@WoodrowShigeru thanks for the update, I added a notice about Adblocker to the [troubleshooting](https://github.com/trapias/TrelloExport/wiki/Troubleshooting) wiki page.
