### ISSUE TITLE
Export Done and Done By is missing

### ISSUE THREAD

**Issue by celestescleaningclub** [trapias/TrelloExport#55]
I have uploaded the export, a screenshot of the options used to export.  I can export a copy of the json file if that is useful but I don't have authority to give you access to the board.  

I select Done and Archive The issues in the Archive are missing the Done date and Done By but when I look at the history in the card, I can see the card move to Done with a date and a person.  

<img width="627" alt="screen shot 2018-09-17 at 19 08 04" src="https://user-images.githubusercontent.com/43093272/45638313-281e8f00-baad-11e8-9294-7a3af5c7f34e.png">
<img width="942" alt="screen shot 2018-09-17 at 19 01 42" src="https://user-images.githubusercontent.com/43093272/45638314-281e8f00-baad-11e8-9109-2ae9a6d07874.png">
[TrelloExport_20180917190219.xlsx](https://github.com/trapias/TrelloExport/files/2389540/TrelloExport_20180917190219.xlsx)

**Comment by celestescleaningclub** [comment]
Hi, is there an update?  Do you need any more information.  The issue is in the archived cards from Done lists.  The list name is Done.  Some of the archive cards are ok (about half) but the rest are not.

**Comment by trapias** [comment]
@celestescleaningclub sorry didn't find the time to look into this yet

**Comment by trapias** [comment]
@celestescleaningclub I just made a test with a board of mine having archived cards, and I can get the "done" data there. Really need you to share a test board with me to look into this.

**Comment by celestescleaningclub** [comment]
ok, I am guessing I need to share this board, not a test board.    Let me
ask the client.

**Comment by celestescleaningclub** [comment]
here is a test board.  i have recreated the issue  see test card and test card 2
feel free to add cards as needed.  this is a test board. 
to recreate I added a card in the first column,  added a member, then moved the card around
put the card in done, removed the member and then archive
https://trello.com/invite/b/qN69R36j/7ac14b22c28e3eaf7328dbf7359a33b8/write-edit-sample-board
[TrelloExport_20181019053517.xlsx](https://github.com/trapias/TrelloExport/files/2494408/TrelloExport_20181019053517.xlsx)

**Comment by trapias** [comment]
@celestescleaningclub I could reproduce the problem but then never found the time to go on, sorry cannot give a timing

**Comment by celestescleaningclub** [comment]
great news that you can recreate.  I will check back next month for an update.

**Comment by trapias** [comment]
@celestescleaningclub fixed, coming with next version later today

**Comment by jlastwood** [comment]
I tried the export with the test board and our live board and I am still missing Done Date and Done By values in Archived cards on export.  I have 1.9.62 and ran the "clear cache button"   Is there something else I should do?

**Comment by trapias** [comment]
@jlastwood I just made a test exporting the Done list, with the "archived" option on, from the test board at https://trello.com/b/qN69R36j/write-edit-sample-board and I can see the columns populated, both on Mac and Windows - see screenshot.


<img width="1467" alt="Schermata 2019-03-21 alle 18 28 18" src="https://user-images.githubusercontent.com/2881610/54772210-3342ab00-4c07-11e9-8b35-8b318cdd30fa.png">

**Comment by jlastwood** [comment]
What about Card 12?

**Comment by trapias** [comment]
@jlastwood I didn't check the code, but most probably the Done data for that card is not extracted because the last move action for that card was not to move it to list 7, but to list 1.

**Comment by jlastwood** [comment]
so if the last action is not Move to Done, then the done data is not completed.  I see this in this example.   There is no Done or Done By information.  It was not moved out of the Done list but they continue to update checklists after it is done.  

![image](https://user-images.githubusercontent.com/11048971/54772842-8c5f0e80-4c08-11e9-9130-2b97d9d910a4.png)

The first item is missing as it was added to Done
![image](https://user-images.githubusercontent.com/11048971/54772986-e7910100-4c08-11e9-8cd0-10cd64d82d80.png)

**Comment by jlastwood** [comment]
It seems to be improved.  Thank you.

**Comment by rmmal** [comment]
can you refer to #73 and tell me what cause the problem ?
