### ISSUE TITLE
"TypeError d.toLocaleDateString is not a function" when exporting comments to Markdown

### ISSUE THREAD

**Issue by acsr** [trapias/TrelloExport#56]
When exporting a whole Trello board to Markdown, selecting the "Comments" as option in any combination with other options or solitaire results in the Red Error Alert "TypeError d.toLocaleDateString is not a function" and failure to export.

No further investigation in console or looking for critical content was done for now.

Exporting the same board to Excel with selecting "Comments" as option works.

Software AddOn Version 1.9.60 in Chrome Version 69.0.3497.100 (Official Build) (64-Bit) on MacOSX 10.11.6

<img width="209" alt="screenshot-typeerror" src="https://user-images.githubusercontent.com/400035/46817180-dfda5000-cd7e-11e8-9eba-870c771256c7.png">
<img width="655" alt="screenshotexport setting" src="https://user-images.githubusercontent.com/400035/46817181-dfda5000-cd7e-11e8-99e5-900fd6565b03.png">

**Comment by trapias** [comment]
@acsr will look into this as soon as I can, could you share a test board with me so to do this faster?

**Comment by trapias** [comment]
Solved with version 1.9.61
