### ISSUE TITLE
Setting custom stylesheet

### ISSUE THREAD

**Issue by Garywoo** [trapias/TrelloExport#60]
In the export options, I can see the field showing the location of the stylesheet, which by default is shown as `chrome-extension://<Extension ID>/templates/default.css`. I have tried to change this value to use a custom stylesheet, but I've had no luck in getting this to work.

I've tried values like `C:\Users\<Me>\Documents\trelloexport.css` and `file:///C:/Users/<Me>/Documents/trelloexport.css`, however these aren't being applied on the output HTML file.

I noticed the value of the Stylesheet field does not change from default.css, even when I choose another template, i.e. _Bibliography HTML_. 

I'm not clear on the behaviour of this field, or how it's supposed to work, and I couldn't find any documentation on the subject. Could anyone give me any insight?

**Comment by trapias** [comment]
@Garywoo you can only load custom stylesheets and template sets (see 
https://trapias.github.io/blog/2018/04/27/TrelloExport-1.9.43) from https sources.

**Comment by Garywoo** [comment]
Thanks @trapias. 
So if I'm understanding things correctly, the _Stylesheet_ field in the export options will only load external stylesheets via https, and only when there is no stylesheet specified in the template selected?

**Comment by trapias** [comment]
@Garywoo yes, only HTTPS sources are allowed; TE should use the custom stylesheet if you configure it, instead of the default one / the one from the chosen template.

**Comment by Garywoo** [comment]
@trapias I'm still having trouble getting this to work.
I'm referencing [this stylesheet](https://gist.githubusercontent.com/Garywoo/a6cbcdf6aa7abd3ff0216ed951759be0/raw/87be7fa2259184327fc12056d48622961d312f9d/trelloexport.css), and selecting the _Bibliography HTML_ template. I'm leaving the Template set field blank.
The given styles in the HTML aren't being applied. I only see references to bibliography.css in the HTML.
