### ISSUE TITLE
Documentation for filters feature?

### ISSUE THREAD

**Issue by Zettt** [trapias/TrelloExport#62]
Hello,

I'm trying to wrap my head around the filter feature. As far as I can tell, there is no documentation on the feature though. I'd like to match two specific lists for the export. How would I go about it using TrelloExport?

Thank you.

**Comment by trapias** [comment]
@Zettt,
sorry I must have missed a notification for this issue :-(
Filters act on the item selected in the dropdown, e.g. List names, which are searched comparing your filter string with a “contains” method - for example filter lists whose name contains your filter string.
The filter string is now a single string, so in your case it might help if both list contain some string - e.g. “ListOne” and “ListTwo” should match a filter string like “

Maybe we could let the filter string become “filter strings”, for example a comma separated list of filter strings (like “filter1,  Would this help you?
