### ISSUE TITLE
Download does not initiate when button is clicked (1.9.63)

### ISSUE THREAD

**Issue by mge501** [trapias/TrelloExport#68]
Just trying to resolve something on behalf of a colleague - she is working on a remote desktop and when she clicks the "Export" button, the usual popup at top right of screen to indicate that download has started does not appear. All settings appear to be correct but the file will not download.

The export function works fine when she runs it on her own PC, i.e. not connected to remote desktop. It also works fine for me in both my remote desktop and my own PC. 

Any ideas for settings we might *not* have checked? She is using Chrome, and her extension settings are the same as mine. 

If you can't tell I am a complete rookie at this so answers in short words please!! Any suggestions much appreciated

**Comment by trapias** [comment]
Mmm.. maybe something with user permissions? Does she have permissions to save files to the local disk when she’s on that Remote Desktop?

**Comment by mge501** [comment]
I *think* she does (she's downloaded other files successfully) but I will
suggest that she checks the permissions relating specifically to Trello.
The remote desktop she's working on is her own office PC, so in theory
there should be nothing unexpected going on, but worth checking.

Thanks for getting back to me, it's appreciated.
