### ISSUE TITLE
Excel says it has found a problem with some content in the workbook

### ISSUE THREAD

**Issue by jlvanoorschot** [trapias/TrelloExport#7]
Hi, 

There's nothing special in my boarrd I think, but for some reason it won't export well. I tried exporting the Welcome board and that exports fine. However, the xlsx file for this board: https://trello.com/b/sRM2Rr2d won't be opened by both Excel (2016, Win10) and Google Docs.

The board has been set to public and all other extensions are disabled. Still no result. Could you hint me in the right direction?

[Graduation Project (1).xlsx](https://github.com/trapias/TrelloExport/files/182381/Graduation.Project.1.xlsx)

**Comment by trapias** [comment]
@jlvanoorschot very strange: I just tried exporting this board and got a valid file (see below), yet the file you put here cannot be opened. Looks like it's corrupt, it's only 7Kb against about 42kb of mine (exporting all board): if you look at browser console, do you see errors when exporting that board?


[TrelloExport_20160322182936.xlsx](https://github.com/trapias/TrelloExport/files/184637/TrelloExport_20160322182936.xlsx)

**Comment by jlvanoorschot** [comment]
Thanks for your swift reply! I tried it on a different machine and it works perfectly there too. I'll try the machine I used earlier as well and see if that still doesn't work.

**Comment by trapias** [comment]
Oh well, let me know if you get problems. BTW, Windows or Mac?

**Comment by trapias** [comment]
@jlvanoorschot I'm closing this, if you get other problems please comment here
