### ISSUE TITLE
The [Clean LocalStorage] Button Appears On Top Of The [Export Columns] List

### ISSUE THREAD

**Issue by WongZeHao** [trapias/TrelloExport#70]
Hi there,

I experienced the [Clean LocalStorage] button always appears on top of the [Export Columns]'s List and blocking part of it, as shown in Figure 1.

By the way, it is supposed to be [Clean Local Storage], isn't it? I am not sure. 😊 

![TrelloExport  Issue](https://user-images.githubusercontent.com/51298903/80298247-f60efc00-87bc-11ea-8a6b-000d992580dc.jpg)
_Figure 1: The [Clean LocalStorage] button blocks the [Export Columns]'s list._

**Comment by trapias** [comment]
Hello,
are you on Windows? What screen resolution?

**Comment by WongZeHao** [comment]
Hello,

I am on Windows 10 and my screen resolution is 1920 x 1080.

**Comment by trapias** [comment]
Should have been solved with version 1.9.64, can you confirm?

**Comment by WongZeHao** [comment]
I have confirmed with version 1.9.64. It is solved. Thank you.
