### ISSUE TITLE
Excel Format: Archived Cards are not exported from Version 1.9.64

### ISSUE THREAD

**Issue by rachoski** [trapias/TrelloExport#72]
Hello Luis,

With the latest update (1.9.64), I´m not able to export archived cards in Excel format. Creates the sheet for archived cards but it is not populated. Tested in Chrome and Edge, (all with latest updates in browsers and OS). Tested in 2 different machines.

As a work around, in CSV mode, you can export all cards in one file.  (titles twice) .

Regards and thanks for your effort...
José

**Comment by trapias** [comment]
Issue fixed with version 1.9.65
