### ISSUE TITLE
Done and Done-by coloumn 

### ISSUE THREAD

**Issue by rmmal** [trapias/TrelloExport#73]
I have 4 cards in a board:

card number 1
![image](https://user-images.githubusercontent.com/6699411/89202359-1f58d880-d5b3-11ea-8084-55deeb4c170d.png)

card number 2 
![image](https://user-images.githubusercontent.com/6699411/89202413-33043f00-d5b3-11ea-8050-827de69b6d23.png)

card number 3
![image](https://user-images.githubusercontent.com/6699411/89202436-3992b680-d5b3-11ea-9ccc-da9445331ce4.png)

card number 4
![image](https://user-images.githubusercontent.com/6699411/89202455-40b9c480-d5b3-11ea-825c-833c7afc3720.png)

when export to excel , this is the output 
![image](https://user-images.githubusercontent.com/6699411/89202472-49aa9600-d5b3-11ea-90b6-e494ec235f33.png)

the 2nd and 3rd only have done date.

Can anyone explain ?

**Comment by rmmal** [comment]
I created another new board with these coloumn and it is working fine,

So I don't know why the above board is not working ?! 
Any suggestions ?

**Comment by rmmal** [comment]
Update: 
The new board that was working fine stopped adding any done date after adding a new member to some cards.
Now it is not working at all.

**Comment by rmmal** [comment]
I have 4 cards , all of them 

card number 1
![image](https://user-images.githubusercontent.com/6699411/89202359-1f58d880-d5b3-11ea-8084-55deeb4c170d.png)

card number 2 
![image](https://user-images.githubusercontent.com/6699411/89202413-33043f00-d5b3-11ea-8050-827de69b6d23.png)

card number 3
![image](https://user-images.githubusercontent.com/6699411/89202436-3992b680-d5b3-11ea-9ccc-da9445331ce4.png)

card number 4
![image](https://user-images.githubusercontent.com/6699411/89202455-40b9c480-d5b3-11ea-825c-833c7afc3720.png)

when export to excel , this is the output 
![image](https://user-images.githubusercontent.com/6699411/89202472-49aa9600-d5b3-11ea-90b6-e494ec235f33.png)

the 2nd and 3rd only have done date.

Can anyone explain ?

**Comment by trapias** [comment]
@rmmal did you check this wiki page https://github.com/trapias/TrelloExport/wiki/Done ?
