### ISSUE TITLE
Additional columns with extra (trash) data

### ISSUE THREAD

**Issue by optimeadmin** [trapias/TrelloExport#74]
We encounter that if you don't refresh the page before exporting with TrelloExport, the final file will have extra (trash) data at the end of the file.

BEFORE REFRESHING
![image](https://user-images.githubusercontent.com/70289611/94581401-0da94f80-0249-11eb-869b-1924f6948978.png)

AFTER REFRESHING
![image](https://user-images.githubusercontent.com/70289611/94581544-3893a380-0249-11eb-90a7-0dc115497df3.png)

Below the download configuration:
EXPORT TO: CSV / Excel
EXPORT: Archived items, Custom Fields
ONE ROW PER EACH: Card
EXPORT COLUMN: ALL SELECTED
DONE LIST NAME: Done
FILTER: On List Name
TYPE OF EXPORT: Current Board / Multiple Boards

TrelloExport Version: 1.9.65
Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by trapias** [comment]
@optimeadmin I never noticed this, still happening? Windows or Mac?
