### ISSUE TITLE
Double header when exporting CSV with Archive items

### ISSUE THREAD

**Issue by optimeadmin** [trapias/TrelloExport#76]
Howdy!
We notice that when we export a CSV file with Archive items, the final file comes with two headers (one extra for Archive items).

![image](https://user-images.githubusercontent.com/70289611/94589683-96c58400-0253-11eb-9128-efaccedbe8c9.png)

Below the download configuration:
EXPORT TO: CSV
EXPORT: Archived items, Custom Fields
ONE ROW PER EACH: Card
EXPORT COLUMN: ALL SELECTED
DONE LIST NAME: Done
FILTER: On List Name
TYPE OF EXPORT: Current Board / Multiple Boards

TrelloExport Version: 1.9.65
Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by trapias** [comment]
@optimeadmin yes the CSV export handles archived items this way... maybe I just can avoid the double header line, did you mean this?

**Comment by trapias** [comment]
@optimeadmin  version 1.9.68 waiting for approval at the Chrome web store
