### ISSUE TITLE
Advanced Checklists - due date

### ISSUE THREAD

**Issue by suebee68** [trapias/TrelloExport#78]
When I export my data, I export checklists with 1 row for each checklist.  I'm using the new Trello Advanced Checklists feature that allows for due dates for each checklist item.  Currently, the exported Excel file lists the card due date for each checklist item.  

My ability  to use your product is dependent on including the checklist due date so I can filter, sort, etc by checklist item due date.  Please, please add this feature.  I would be happy to contribute to your cause if this were available.

Incidentally, the advanced checklists also allow for entry of an "assigned to" user.  I don't use that field but others may find it useful to export this info.

**Comment by trapias** [comment]
@suebee68 this is only available for Trello Business accounts, isn't it? I could try to look at it, but I'd need to access a board where the "advanced checklist " feature is enabled.

**Comment by suebee68** [comment]
???  i sent this question months ago an sc hav edd since downgrsded my
trello plan

**Comment by trapias** [comment]
Sorry it's hard for me to find the time to continuously monitor issues
