### ISSUE TITLE
A bug when you export multi-byte character cards to markdown format

### ISSUE THREAD

**Issue by wukuan405** [trapias/TrelloExport#8]
## Bug report
when you export multi-byte character cards to markdown format, such as Japanese,
the characters will be wrong as following sample.
But the excel format is no problem.

## Bug data sample
```
**Description:**
&#28961;&#26009;&#12391;&#12289;&#28023;&#22806;&#36009;&#22770;&#12364;&#12391;&#12365;&#12427;&#12493;&#12483;&#12488;&#12471;&#12519;&#12483;&#12503;&#38283;&#26989;&#12469;&#12540;&#12499;&#12473;&#12290;&#12377;&#12391;&#12395;&#22269;&#20869;&#12471;&#12519;&#12483;&#12503;&#12434;&#36939;&#21942;&#12373;&#12428;&#12390;&#12427;
```
## Suggestion
you'd better check the encoding or utf configuration at the markdown format export parts.

**Comment by trapias** [comment]
@wukuan405 could you please provide a public board on which to test, or add some Japanese text to TrelloExport board at https://trello.com/b/MBnwUMwM/trelloexport ?

**Comment by trapias** [comment]
@wukuan405 also here it looks like to work correctly, here's your text pasted in editor:

&#28961;&#26009;&#12391;&#12289;&#28023;&#22806;&#36009;&#22770;&#12364;&#12391;&#12365;&#12427;&#12493;&#12483;&#12488;&#12471;&#12519;&#12483;&#12503;&#38283;&#26989;&#12469;&#12540;&#12499;&#12473;&#12290;&#12377;&#12391;&#12395;&#22269;&#20869;&#12471;&#12519;&#12483;&#12503;&#12434;&#36939;&#21942;&#12373;&#12428;&#12390;&#12427;

**Comment by wukuan405** [comment]
the right side is correct!

**Comment by wukuan405** [comment]
https://trello.com/c/JXcY0d28
here is the japanese test data, please try it.

**Comment by trapias** [comment]
@wukuan405 the exported file is UTF8 and I believe characters are correctly encoded, the only problem I see is the javascript code is not rendered, but that's because the proper markdown syntax for a code section should be used.

<img width="1044" alt="trelloexport_20160519163723_md_e_turms_-_software_for_event_freighting" src="https://cloud.githubusercontent.com/assets/2881610/15400191/efd1cd58-1dea-11e6-959f-307ee6d9ba55.png">

<img width="1042" alt="trelloexport_20160519163723_md" src="https://cloud.githubusercontent.com/assets/2881610/15400243/2445fdfc-1deb-11e6-9bdb-8a803582e18c.png">

**Comment by wukuan405** [comment]
You are right, but why the export of the markdown file could not be the readable characters.
I found following resources which might be valuable for you to check.
https://github.com/harisenbon/autokana
http://www.nishishi.com/javascript/2007/encodeuri.html
best regards,

**Comment by trapias** [comment]
@wukuan405 I'm looking into this issue. At the moment, the best solution I have is still to encode this way, so to avoid any error and be able to open (and read) both the produced .md and .html files, but it's true only special chars should be encoded in markdown, that is:

```
\  backslash 
`  backtick 
*  asterisk 
_  underscore 
{} curly braces 
[] square brackets 
() parentheses 
#  hash mark 
>  greater than 
+  plus sign 
-  minus sign (hyphen) 
.  dot 
!  exclamation mark
```

Will try to find a better solution!

**Comment by trapias** [comment]
@wukuan405 I got it, will commit a new release fixing the problem very soon
