### ISSUE TITLE
Start Date is not included in the export file

### ISSUE THREAD

**Issue by htripi** [trapias/TrelloExport#84]
I need to export the field "start date" but apparently it is not included in the excel file.
I am attaching an image with the field
![image](https://user-images.githubusercontent.com/62359404/123268739-b3d26f00-d4d4-11eb-8861-e574f93502fd.png)
![image](https://user-images.githubusercontent.com/62359404/123268789-c0ef5e00-d4d4-11eb-9029-c3a3a02447f6.png)

Thanks in advance

**Comment by trapias** [comment]
@htripi yes we're missing this field at the moment, will add ASAP

**Comment by htripi** [comment]
@trapias thank you very much!

**Comment by trapias** [comment]
@htripi version 1.9.68 waiting for approval at the Chrome web store

**Comment by htripi** [comment]
Great!. Thanks
