### ISSUE TITLE
"Spent" export 

### ISSUE THREAD

**Issue by brunovandenbroucke** [trapias/TrelloExport#88]
"Spent" export from "plus for trello" doesn't work since Trelloexport 1.9.70 

https://trello.com/b/o4RvpkHm/testspentplustrelloexport

**Comment by trapias** [comment]
@brunovandenbroucke you have to enable the exporting of comments:

![image](https://user-images.githubusercontent.com/2881610/140553377-885f5a72-5819-435d-96a1-896314981853.png)

![image](https://user-images.githubusercontent.com/2881610/140553246-ff53d931-4674-45dc-84d3-e0249915e8f6.png)

**Comment by brunovandenbroucke** [comment]
Thank you very much

Bruno Van Den Broucke
31 rue de Pollux 44700 Orvault
06 28 21 00 77
