### ISSUE TITLE
Checklist Due Dates

### ISSUE THREAD

**Issue by RedBeard4** [trapias/TrelloExport#89]
Good afternoon, I am new to GitHub so I hope I am following protocol. This export tool is excellent and greatly appreciated. I was wondering if the checklist due dates associated wit a card were supposed to be exported. If not, could that be added to the export options. Thank you for considering my request.

**Comment by albertovelo** [comment]
@RedBeard4 I'm not sure, but think this is only available to business users - see https://github.com/trapias/TrelloExport/issues/78.

If this is the case, please share a board with me so that I can try to look into this.

Thank you,
Alberto.
