### ISSUE TITLE
How to donate $$?

### ISSUE THREAD

**Issue by samakshjain** [trapias/TrelloExport#9]

**Comment by trapias** [comment]
@samakshjain what a good question! 😄 

I have a page on my site for this, see http://trapias.github.io/donate/ - but it's basically just a link to PayPal, with which you can donate going to https://www.paypal.me/AlbertoVelo.

Thank you!

**Comment by samakshjain** [comment]
> Unfortunately PayPal.Me isn't available in your country.
FYI, I'm from India. Take this `grazie` if that can't be resolved. :)

**Comment by trapias** [comment]
@samakshjain uh, I did open an account which is linked to my Paypal, I assumed it's working - did you try to make a donation? What happened? Just to understand, of course a "grazie" is enough! :-)

**Comment by samakshjain** [comment]
Paypal worked for me :)

**Comment by trapias** [comment]
Hello Samaksh,
thank you very much!!!

Alberto.

**Comment by trapias** [comment]
@samakshjain thank you so much!
