### ISSUE TITLE
"TypeError d.toLocaleDateString is not a function" when exporting comments to OPML

### ISSUE THREAD

**Issue by cnpgs** [trapias/TrelloExport#91]
When exporting a Trello board to OPML, selecting the "Comments" as an option (either by itself or in conjunction with other options) shows the error "TypeError d.toLocaleDateString is not a function". 

Potentially related to closed issue https://github.com/trapias/TrelloExport/issues/56, which exhibited similar behaviour but for Markdown export.

![image](https://github.com/trapias/TrelloExport/assets/22747334/6ed371c9-6d9c-484f-a4ca-c4fcc51a9e57)

**Comment by trapias** [comment]
@cnpgs should be solved with version 1.9.7.3, available here and soon at the Chrome web store

**Comment by cnpgs** [comment]
@trapias Great, many thanks for the speedy response!
